CREATE TABLE sys_user
(
	id        VARCHAR2(32) NOT NULL,
	create_by VARCHAR2(32) DEFAULT '' NOT NULL,
	create_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	update_by VARCHAR2(32),
	update_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
	name      VARCHAR2(32) NOT NULL,
	password  VARCHAR2(64) NOT NULL,
	delete_at TIMESTAMP(6) DEFAULT NULL,
	CONSTRAINT sys_user_id_pkey PRIMARY KEY (id)
);
